package homework2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.8
 * 2024-03-31T23:44:25.234+02:00
 * Generated source version: 3.5.8
 *
 */
@WebServiceClient(name = "PizzaPriceServiceImpService",
                  wsdlLocation = "http://127.0.0.1:8001/Price?wsdl",
                  targetNamespace = "http://homework2/")
public class PizzaPriceServiceImpService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://homework2/", "PizzaPriceServiceImpService");
    public static final QName PizzaPriceServiceImpPort = new QName("http://homework2/", "PizzaPriceServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8001/Price?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PizzaPriceServiceImpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8001/Price?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PizzaPriceServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PizzaPriceServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PizzaPriceServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PizzaPriceServiceImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PizzaPriceServiceImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PizzaPriceServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PizzaPriceService
     */
    @WebEndpoint(name = "PizzaPriceServiceImpPort")
    public PizzaPriceService getPizzaPriceServiceImpPort() {
        return super.getPort(PizzaPriceServiceImpPort, PizzaPriceService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PizzaPriceService
     */
    @WebEndpoint(name = "PizzaPriceServiceImpPort")
    public PizzaPriceService getPizzaPriceServiceImpPort(WebServiceFeature... features) {
        return super.getPort(PizzaPriceServiceImpPort, PizzaPriceService.class, features);
    }

}
