
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package homework2;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.8
 * 2024-03-31T23:44:25.220+02:00
 * Generated source version: 3.5.8
 *
 */

@javax.jws.WebService(
                      serviceName = "PizzaPriceServiceImpService",
                      portName = "PizzaPriceServiceImpPort",
                      targetNamespace = "http://homework2/",
                      wsdlLocation = "http://127.0.0.1:8001/Price?wsdl",
                      endpointInterface = "homework2.PizzaPriceService")

public class PizzaPriceServiceImpPortImpl implements PizzaPriceService {

    private static final Logger LOG = Logger.getLogger(PizzaPriceServiceImpPortImpl.class.getName());

    /* (non-Javadoc)
     * @see homework2.PizzaPriceService#getPizzaPrice(java.lang.String arg0, int arg1)*
     */
    public double getPizzaPrice(java.lang.String arg0, int arg1) {
        LOG.info("Executing operation getPizzaPrice");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            double _return = 0.3245735063808256;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see homework2.PizzaPriceService#getPizzaSpecialOffers(java.lang.String arg0)*
     */
    public java.lang.String getPizzaSpecialOffers(java.lang.String arg0) {
        LOG.info("Executing operation getPizzaSpecialOffers");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return899566481";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
