
package homework2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.8
 * 2024-03-31T23:44:25.170+02:00
 * Generated source version: 3.5.8
 *
 */
public final class PizzaPriceService_PizzaPriceServiceImpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://homework2/", "PizzaPriceServiceImpService");

    private PizzaPriceService_PizzaPriceServiceImpPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PizzaPriceServiceImpService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PizzaPriceServiceImpService ss = new PizzaPriceServiceImpService(wsdlURL, SERVICE_NAME);
        PizzaPriceService port = ss.getPizzaPriceServiceImpPort();

        {
        System.out.println("Invoking getPizzaPrice...");
        java.lang.String _getPizzaPrice_arg0 = "_getPizzaPrice_arg02094109859";
        int _getPizzaPrice_arg1 = 1110864032;
        double _getPizzaPrice__return = port.getPizzaPrice(_getPizzaPrice_arg0, _getPizzaPrice_arg1);
        System.out.println("getPizzaPrice.result=" + _getPizzaPrice__return);


        }
        {
        System.out.println("Invoking getPizzaSpecialOffers...");
        java.lang.String _getPizzaSpecialOffers_arg0 = "_getPizzaSpecialOffers_arg01877350435";
        java.lang.String _getPizzaSpecialOffers__return = port.getPizzaSpecialOffers(_getPizzaSpecialOffers_arg0);
        System.out.println("getPizzaSpecialOffers.result=" + _getPizzaSpecialOffers__return);


        }

        System.exit(0);
    }

}
