
package pizzaPrice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.8
 * Sun Mar 31 23:48:23 CEST 2024
 * Generated source version: 3.5.8
 */

@XmlRootElement(name = "getPizzaPriceResponse", namespace = "http://pizzaPrice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPizzaPriceResponse", namespace = "http://pizzaPrice/")

public class GetPizzaPriceResponse {

    @XmlElement(name = "return")
    private double _return;

    public double getReturn() {
        return this._return;
    }

    public void setReturn(double new_return)  {
        this._return = new_return;
    }

}

