
package pizzaPrice.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.8
 * Sun Mar 31 23:48:23 CEST 2024
 * Generated source version: 3.5.8
 */

@XmlRootElement(name = "getPizzaSpecialOffers", namespace = "http://pizzaPrice/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPizzaSpecialOffers", namespace = "http://pizzaPrice/")

public class GetPizzaSpecialOffers {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

